In [10]:
import numpy as np

In [11]:
w1 = np.array([[1, 2], [3, 4]])
w2 = np.array([[1, 2]])
b1 = np.array([1, -1])
b2 = np.array([1])
x = np.array([[1, 0], [0, 1]])
y = np.array([[1], [0]])

In [12]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_prime(x):
    return sigmoid(x) * (1 - sigmoid(x))

def relu(x):
    return np.maximum(0, x)

def relu_prime(x):
    return np.where(x > 0, 1, 0)

In [13]:
# forward prop
print("\nz2")
z2 = np.dot(x, w1.T) + b1
print(z2)
print("\na2")
a2 = relu(z2)
print(a2)


z2
[[2 2]
 [3 3]]

a2
[[2 2]
 [3 3]]


In [14]:
print("\nz3")
z3 = np.dot(a2, w2.T) + b2
print(z3)
print("\na3")
a3 = sigmoid(z3)
print(a3)


z3
[[ 7]
 [10]]

a3
[[0.99908895]
 [0.9999546 ]]


In [15]:
# backward prop
print("\ndelta3")
delta3 = (a3 - y) * sigmoid_prime(z3)
print(delta3)
print("\ndJdW2")
dJdW2 = np.dot(delta3.T, a2)
print(dJdW2)


delta3
[[-8.29258093e-07]
 [ 4.53937469e-05]]

dJdW2
[[0.00013452 0.00013452]]


In [16]:
print("\ndelta2")
delta2 = np.dot(delta3, w2) * relu_prime(z2)
print(delta2)
print("\ndJdW1")
dJdW1 = np.dot(delta2.T, x)
print(dJdW1)


delta2
[[-8.29258093e-07 -1.65851619e-06]
 [ 4.53937469e-05  9.07874937e-05]]

dJdW1
[[-8.29258093e-07  4.53937469e-05]
 [-1.65851619e-06  9.07874937e-05]]


In [17]:
print("dJdb1")
dJdb1 = np.sum(delta2, axis=0)
print(dJdb1)
print("dJdb2")
dJdb2 = np.sum(delta3, axis=0)
print(dJdb2)

dJdb1
[4.45644888e-05 8.91289775e-05]
dJdb2
[4.45644888e-05]


In [18]:
alpha = 1

w1 = w1 - alpha * dJdW1
w2 = w2 - alpha * dJdW2
b1 = b1 - alpha * dJdb1
b2 = b2 - alpha * dJdb2

print("\nw1")
print(w1)
print("\nb1")
print(b1)
print("\nw2")
print(w2)
print("\nb2")
print(b2)


w1
[[1.00000083 1.99995461]
 [3.00000166 3.99990921]]

w2
[[0.99986548 1.99986548]]

b1
[ 0.99995544 -1.00008913]

b2
[0.99995544]
